/* Generate dist/deck.body.html from the built game.
   ------------------------------------------------------------------
   deck.body.html is the embeddable fragment: the built page without
   the <!doctype>/<html>/<head>/<body> wrapper, with the bundle inlined
   rather than linked, because an embedded fragment cannot rely on the
   host page serving assets from the right path.

   It used to be generated by concatenating the source scripts, which
   only worked while they were classic scripts. Now Vite does the
   bundling and this only has to flatten what Vite emitted — which
   also means the fragment is the same code the real build ships
   rather than a second assembly of it.

   It is a build artifact now, not a committed file: it changes on
   every source change and dist/ is ignored.

   Runs as part of `npm run build`, after `vite build`:

     node tools/build-body.mjs
*/

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DIST = join(dirname(fileURLToPath(import.meta.url)), "..", "dist");
const PAGE = join(DIST, "index.html");

if (!existsSync(PAGE)) {
  console.error("dist/index.html is missing. Run: npm run build");
  process.exit(1);
}

let out = readFileSync(PAGE, "utf8");
let inlined = 0;

/* inline the module bundle */
out = out.replace(
  /<script([^>]*?)\ssrc=["']\.?\/?([^"']+)["']([^>]*)><\/script>/g,
  (_, pre, file, post) => {
    inlined++;
    const js = readFileSync(join(DIST, file), "utf8").trimEnd();
    const type = /type=["']module["']/.test(pre + post) ? ' type="module"' : "";
    return `<script${type}>\n/* --- inlined from ${file} by tools/build-body.mjs --- */\n${js}\n</script>`;
  }
);

/* inline any stylesheet Vite emitted. The page's own <style> block is
   already inline; this catches anything a later build extracts. */
out = out.replace(
  /<link[^>]*rel=["']stylesheet["'][^>]*href=["'](?!https?:)\.?\/?([^"']+)["'][^>]*>/g,
  (_, file) => {
    inlined++;
    return `<style>\n${readFileSync(join(DIST, file), "utf8").trimEnd()}\n</style>`;
  }
);

/* drop the document wrapper; keep title, links, style, markup, script */
const start = out.indexOf("<title");
if (start < 0) throw new Error("could not find the <title> in dist/index.html");
out = out.slice(start)
         .replace(/<\/head>/i, "")
         .replace(/<body[^>]*>/i, "")
         .replace(/<\/body>/i, "")
         .replace(/<\/html>/i, "")
         .replace(/\n{3,}/g, "\n\n")
         .trimEnd() + "\n";

const path = join(DIST, "deck.body.html");
writeFileSync(path, out);
console.log(`dist/deck.body.html  ${out.split("\n").length} lines ` +
            `(${inlined} asset${inlined === 1 ? "" : "s"} inlined, ` +
            `${(out.length / 1024).toFixed(1)} KB)`);
